// <auto-generated />
namespace TunstallDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Alter_Event_EventZone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter_Event_EventZone));
        
        string IMigrationMetadata.Id
        {
            get { return "201902211841162_Alter_Event_EventZone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
